// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiForGauge.Database;

#nullable disable

namespace WebApiForGauge.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251101085235_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiForGauge.Models.PhysicalExercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkoutDayNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDayNumber");

                    b.ToTable("PhysicalExercises");
                });

            modelBuilder.Entity("WebApiForGauge.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkoutProgramId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApiForGauge.Models.WorkoutDay", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkoutProgramId")
                        .HasColumnType("integer");

                    b.HasKey("Number");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("WebApiForGauge.Models.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DaysPerWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FitnessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserWeight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("WebApiForGauge.Models.PhysicalExercises", b =>
                {
                    b.HasOne("WebApiForGauge.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("PhysicalExercises")
                        .HasForeignKey("WorkoutDayNumber");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("WebApiForGauge.Models.User", b =>
                {
                    b.HasOne("WebApiForGauge.Models.WorkoutProgram", "WorkoutProgram")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WebApiForGauge.Models.WorkoutDay", b =>
                {
                    b.HasOne("WebApiForGauge.Models.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("WorkoutProgramId");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WebApiForGauge.Models.WorkoutDay", b =>
                {
                    b.Navigation("PhysicalExercises");
                });

            modelBuilder.Entity("WebApiForGauge.Models.WorkoutProgram", b =>
                {
                    b.Navigation("WorkoutDays");
                });
#pragma warning restore 612, 618
        }
    }
}
